# Conversion
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables"]

highlighter: rouge

# Uncomment if using alternative renderer
# rdiscount:
#  extensions:
#    - autolink

# kramdown:
#  input: GFM

# Serving
destination: ../_site/
baseurl: ""
exclude: ["img/resources/SiteComponents.png","sidebar.html","*/sidebar.html"]

# Variables
product: Aperture Tiles
version: 0.6.0